version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurantdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - restaurant-service
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
